// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddCustomParadigm(arg1:string):Promise<main.ParadigmVersion>;

export function BrowseDirectory(arg1:string):Promise<Array<string>>;

export function GetDefaultParadigmPath():Promise<string>;

export function LaunchParadigm(arg1:string):Promise<boolean>;

export function ScanForParadigmVersions(arg1:string):Promise<Array<main.ParadigmVersion>>;
