// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCustomParadigm(arg1) {
  return window['go']['main']['App']['AddCustomParadigm'](arg1);
}

export function BrowseDirectory(arg1) {
  return window['go']['main']['App']['BrowseDirectory'](arg1);
}

export function GetDefaultParadigmPath() {
  return window['go']['main']['App']['GetDefaultParadigmPath']();
}

export function LaunchParadigm(arg1) {
  return window['go']['main']['App']['LaunchParadigm'](arg1);
}

export function ScanForParadigmVersions(arg1) {
  return window['go']['main']['App']['ScanForParadigmVersions'](arg1);
}
